backend:
  name: github
  repo: Marhead/Marhead.github.io

media_folder: "assets/img"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
    - label: "Website settings"
      name: "site"
      file: "_data/site.yml"
      fields:
        - label: "Tel"
          name: "tel"
          width: "string"